CREATE TABLE IF NOT EXISTS subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id BIGINT REFERENCES users(id) NOT NULL,
    followed_id BIGINT REFERENCES users(id) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    is_subscribed BOOLEAN NOT NULL
);